# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine

TARGETS = \
	MP_CPP-Android-DebugGame  \
	MP_CPP-Android-Development  \
	MP_CPP-Android-Shipping  \
	MP_CPP-Linux-DebugGame  \
	MP_CPP-Linux-Development  \
	MP_CPP-Linux-Shipping  \
	MP_CPP-LinuxArm64-DebugGame  \
	MP_CPP-LinuxArm64-Development  \
	MP_CPP-LinuxArm64-Shipping  \
	MP_CPP \
	MP_CPPEditor-Linux-DebugGame  \
	MP_CPPEditor-Linux-Development  \
	MP_CPPEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MP_CPPEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MP_CPPEditor-Linux-Debug


MP_CPP-Android-DebugGame:
	 $(BUILD) MP_CPP Android DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-Android-Development:
	 $(BUILD) MP_CPP Android Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-Android-Shipping:
	 $(BUILD) MP_CPP Android Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-Linux-DebugGame:
	 $(BUILD) MP_CPP Linux DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-Linux-Development:
	 $(BUILD) MP_CPP Linux Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-Linux-Shipping:
	 $(BUILD) MP_CPP Linux Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-LinuxArm64-DebugGame:
	 $(BUILD) MP_CPP LinuxArm64 DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-LinuxArm64-Development:
	 $(BUILD) MP_CPP LinuxArm64 Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP-LinuxArm64-Shipping:
	 $(BUILD) MP_CPP LinuxArm64 Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPP: MP_CPP-Linux-Development

MP_CPPEditor-Linux-DebugGame:
	 $(BUILD) MP_CPPEditor Linux DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPPEditor-Linux-Development:
	 $(BUILD) MP_CPPEditor Linux Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" $(ARGS)

MP_CPPEditor: MP_CPPEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MP_CPP/MP_CPP.uproject" -Game 

.PHONY: $(TARGETS)
